import { test, expect } from '@playwright/test';
import { DEMO_ACCOUNTS } from '../../src/shared/demo-data';

const [a, b] = DEMO_ACCOUNTS;
test('PF-025-L: nota/estado persistem por conta, filtros e denominador; edição antiga/CSRF recusados', async ({ page }) => {
  const issues: string[] = [];
  page.on('pageerror', () => issues.push('pageerror'));
  page.on('console', (message) => { if (message.type() === 'error' && !message.text().startsWith('Failed to load resource:')) issues.push('console_error'); });
  await page.goto('/'); await page.getByRole('button', { name: 'Entrar como operador fictício' }).click();
  await page.getByRole('link', { name: /Jardim/ }).click();
  const origin = new URL(page.url()).origin, api = `/api/accounts/${b.id}/inbox`;
  expect((await page.request.post(`/api/accounts/${b.id}/simulate-event`, { headers: { Origin: origin }, data: { kind: 'message', text: 'Organização fictícia', externalId: crypto.randomUUID() } })).status()).toBe(200);
  let conversationId = '';
  await expect.poll(async () => {
    const list = await (await page.request.get(api)).json();
    conversationId = list.conversations.find((item: { contact: { igScopedUserId: string } }) => item.contact.igScopedUserId === 'synthetic-visitor')?.id;
    if (!conversationId) return false;
    return (await (await page.request.get(`${api}/${conversationId}`)).json()).messages.some((item: { body: string }) => item.body === 'Organização fictícia');
  }).toBe(true);
  const before = await (await page.request.get(`${api}/${conversationId}`)).json();
  await page.getByRole('button', { name: 'Atualizar inbox' }).click();
  await page.getByRole('button', { name: /Visitante fictício/ }).click();
  await page.getByText('Estado e nota da conversa', { exact: true }).click();
  await page.getByLabel('Estado da conversa', { exact: true }).selectOption('resolved');
  await page.getByLabel('Nota da conversa', { exact: true }).fill('Agendar retorno exclusivo Jardim');
  await page.getByRole('button', { name: 'Salvar estado e nota' }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Estado e nota salvos' })).toBeVisible();
  const current = await (await page.request.get(`${api}/${conversationId}`)).json();
  expect(current.conversation.controlVersion).toBe(before.conversation.controlVersion);
  const stale = { action: 'organize', version: before.conversation.organizationVersion, note: 'Edição atrasada', status: 'open' };
  expect((await page.request.post(`${api}/${conversationId}`, { headers: { Origin: origin }, data: stale })).status()).toBe(409);
  expect((await page.request.post(`${api}/${conversationId}`, { data: stale })).status()).toBe(401);
  expect((await page.request.post(`/api/accounts/${a.id}/inbox/${conversationId}`, { headers: { Origin: origin }, data: stale })).status()).toBe(404);
  await page.reload(); await page.getByRole('button', { name: /Visitante fictício/ }).click();
  await page.getByText('Estado e nota da conversa', { exact: true }).click();
  await expect(page.getByLabel('Nota da conversa', { exact: true })).toHaveValue('Agendar retorno exclusivo Jardim');
  await expect(page.getByLabel('Estado da conversa', { exact: true })).toHaveValue('resolved');
  await page.getByLabel('Filtrar estado', { exact: true }).selectOption('open');
  await page.getByRole('button', { name: 'Aplicar filtros' }).click();
  await expect(page.getByText('Nenhuma conversa neste filtro.')).toBeVisible();
  await page.getByLabel('Filtrar estado', { exact: true }).selectOption('resolved');
  await page.getByLabel('Buscar conversa').fill('RETORNO EXCLUSIVO');
  await page.getByRole('button', { name: 'Aplicar filtros' }).click();
  await expect(page.getByRole('button', { name: /Visitante fictício/ })).toHaveCount(1);
  const filter = await (await page.request.get(`${api}?status=resolved&q=RETORNO`)).json();
  const all = await (await page.request.get(api)).json();
  expect(filter.metrics).toEqual(all.metrics);
  await page.getByLabel('Filtrar controle', { exact: true }).selectOption(current.conversation.control === 'manual' ? 'automatic' : 'manual');
  await page.getByRole('button', { name: 'Aplicar filtros' }).click();
  await expect(page.getByText('Nenhuma conversa neste filtro.')).toBeVisible();
  await page.getByLabel('Filtrar controle', { exact: true }).selectOption(current.conversation.control);
  await page.getByRole('button', { name: 'Aplicar filtros' }).click();
  await expect(page.getByRole('button', { name: /Visitante fictício/ })).toHaveCount(1);
  await page.getByText('Métricas locais do período', { exact: true }).click();
  await expect(page.getByText(/Taxa de aceitação:/)).toContainText(`${all.metrics.accepted} / ${all.metrics.denominator}`);
  await expect(page.getByText('Tentativas não são novas intenções.', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: /Visitante fictício/ }).click();
  await page.getByText('Estado e nota da conversa', { exact: true }).click();
  await page.screenshot({ path: '.local-tools/qa/organization.png', fullPage: true });
  await page.getByLabel('Nota da conversa', { exact: true }).fill('Edição local a preservar');
  expect((await page.request.post(`${api}/${conversationId}`, { headers: { Origin: origin }, data: {
    action: 'organize', version: current.conversation.organizationVersion, status: 'resolved', note: 'Nota de outra sessão',
  } })).status()).toBe(200);
  await page.getByRole('button', { name: 'Salvar estado e nota' }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'A organização da conversa mudou.' })).toBeVisible();
  await expect(page.getByLabel('Nota da conversa', { exact: true })).toHaveValue('Edição local a preservar');
  await page.getByRole('button', { name: 'Atualizar conversa', exact: true }).click();
  await expect(page.getByLabel('Nota da conversa', { exact: true })).toHaveValue('Edição local a preservar');
  await page.getByRole('button', { name: 'Descartar edição da nota' }).click();
  await expect(page.getByLabel('Nota da conversa', { exact: true })).toHaveValue('Nota de outra sessão');
  await page.getByLabel('Nota da conversa', { exact: true }).fill('Agendar retorno exclusivo Jardim');
  await page.getByRole('button', { name: 'Salvar estado e nota' }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Estado e nota salvos' })).toBeVisible();
  await page.getByLabel('Data inicial', { exact: true }).fill('2099-01-01'); await page.getByLabel('Data final', { exact: true }).fill('2099-01-01');
  await page.getByRole('button', { name: 'Aplicar filtros' }).click();
  await expect(page.getByText('Nenhuma conversa neste filtro.')).toBeVisible();
  await page.getByLabel('Data inicial', { exact: true }).fill('2026-09-28'); await page.getByLabel('Data final', { exact: true }).fill('2025-09-28');
  await page.getByRole('button', { name: 'Aplicar filtros' }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'Não foi possível carregar a inbox.' })).toBeVisible();
  await page.getByRole('link', { name: 'Trocar conta' }).click(); await page.getByRole('link', { name: /Aurora/ }).click();
  await expect(page.getByLabel('Buscar conversa')).toHaveValue('');
  await expect(page.getByText('Agendar retorno exclusivo Jardim', { exact: true })).toHaveCount(0);
  expect(issues).toEqual([]);
});
